import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/components/AuthProvider";
import { GlobalProvider } from "@/context/GlobalContext";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";
import Footer from "@/components/Footer"




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Foodie",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await getServerSession({authOptions})
  return (
    
    
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AuthProvider session = {session}>
                  <GlobalProvider>
                    <Navbar/>
                    {children}
                    <ToastContainer
                            position='top-right'
                            autoClose={4000}
                            hideProgressBar={false}
                            newestOnTop={false}
                            closeOnClick
                            rtl={false}
                            pauseOnFocusLoss
                            draggable
                            pauseOnHover
                            style={{ width: "300px" }}
                          />
                    <Footer/>
                  </GlobalProvider>
                </AuthProvider>
            </body>
          </html>
      
    
    
  );
}
